[MTDSA-9086] - Dependency upgrades including play 28
hmrc/individuals-income-received-api pull request #234
Opened 2021-06-07 13:26 UTC by DreamcastKnight

2021-06-07 14:54 UTC, Mbrookesy requested changes
Currently the ATs are failing against the branch, seems to be a lot of rule incorrect body errors.

2021-06-07 14:54 UTC, Mbrookesy commented on app/config/AppConfig.scala
> +  def ifsEnvironmentHeaders: Option[Seq[String]]
Could you add comments above both the DES and IFS lines on line 28 and 33 saying something for each like "DES/IFS Config"

2021-06-07 14:54 UTC, Mbrookesy commented on app/config/AppConfig.scala
> +  def ifsEnvironmentHeaders: Option[Seq[String]]
Could you also add a comment for "API Config" above the API config variables on line 41

2021-06-07 14:54 UTC, Mbrookesy commented on app/config/AppConfig.scala
> +  val ifsEnvironmentHeaders: Option[Seq[String]] = configuration.getOptional[Seq[String]]("microservice.services.ifs.environmentHeaders")
Could you add similar comments to these ones as well matching up with the DES, IFS and API lines

2021-06-07 14:54 UTC, Mbrookesy commented on build.sbt
>    .settings(
Line 64 can be deleted as domain is now deprecated

2021-06-07 14:54 UTC, Mbrookesy commented on build.sbt
> +    ItTest / unmanagedSourceDirectories := Seq((baseDirectory in ItTest).value / "it"),
`baseDirectory in ItTest` needs to be updated to `ItTest / baseDirectory`

2021-06-07 14:54 UTC, Mbrookesy commented on it/v1/endpoints/AddCustomEmploymentControllerISpec.scala
> +          "/startDate"
Could you explain for the controller and validation parts of the pr, why these were changed?

It seems very out of scope these changes.

2021-06-07 14:54 UTC, Mbrookesy commented on project/AppDependencies.scala
> +    "uk.gov.hmrc"        %% "bootstrap-backend-play-28" % "4.3.0",
play 28 can be updated to 5.3.0

2021-06-07 14:54 UTC, Mbrookesy commented on project/AppDependencies.scala
> +    "org.typelevel"      %% "cats-core"                 % "2.6.0",
cats-core can be updated to 2.6.1

2021-06-07 14:54 UTC, Mbrookesy commented on project/AppDependencies.scala
>      "uk.gov.hmrc"        %% "domain"                    % "5.11.0-play-26",
domain can be deleted as it's deprecated

2021-06-07 14:54 UTC, Mbrookesy commented on project/AppDependencies.scala
>      "com.neovisionaries" % "nv-i18n"                    % "1.27"
This can be removed.

2021-06-07 14:54 UTC, Mbrookesy commented on project/AppDependencies.scala
> +    "org.scalatest"          %% "scalatest"          % "3.2.7"             % scope,
This can be updated to 3.2.9

2021-06-07 14:54 UTC, Mbrookesy commented on project/AppDependencies.scala
>      "org.scalacheck"         %% "scalacheck"         % "1.15.1"            % scope,
scalacheck can be 1.15.4

2021-06-07 14:54 UTC, Mbrookesy commented on test/v1/connectors/AddCustomEmploymentConnectorSpec.scala
> +            excludedHeaders = Seq("AnotherHeader" -> "HeaderValue")
[Applies to all the connector specs]

For the connector specs that have a body (PUT/POST) you should add a line before the MockedHttpClient line (For example in this one that would be Line 67)

Something like this: `val requiredDesHeadersPost: Seq[(String, String)] = requiredDesHeaders ++ Seq("Content-Type" -> "application/json")` which basically adds the Content-Type header to it as that would be included in the live version.

2021-06-07 14:54 UTC, Mbrookesy commented on test/v1/connectors/AddCustomEmploymentConnectorSpec.scala
> +            excludedHeaders = Seq("AnotherHeader" -> "HeaderValue")
Could you also include something like above the MockedHttpClient for all of them `implicit val hc: HeaderCarrier = HeaderCarrier(otherHeaders = otherHeaders ++ Seq("Content-Type" -> "application/json"))`

2021-06-07 14:54 UTC, Mbrookesy commented on test/v1/connectors/ConnectorSpec.scala
> +      Some("self-assessment-accounts-api")
This should be `individuals-income-received-api`

2021-06-07 14:54 UTC, Mbrookesy commented on test/v1/connectors/ConnectorSpec.scala
> +      Some("self-assessment-accounts-api")
This should be `individuals-income-received-api`

2021-06-08 07:47 UTC, DreamcastKnight commented on it/v1/endpoints/AddCustomEmploymentControllerISpec.scala
> +          "/startDate"
for some reason, the tests started failing after my changes, switching around the order all the errors were. I hadn't any idea why this was happening, so I changed the tests.

2021-06-10 13:16 UTC, merged