MTDSA-9252 added deleted RAML for CGT PPD Overrides
hmrc/individuals-income-received-api pull request #238
Opened 2021-07-01 10:54 UTC by RachGibbons

2021-07-02 08:39 UTC, jacobbrownlow commented on resources/public/api/conf/1.0/application.raml
> +        name: Report and Pay Capital Gains Tax on Property Overrides
This group name refers only to PPD overrides. Whereas the section will contain both PPD overrides, Non-PPD submissions, and other CGT submissions. A more general name like "Capital Gains Tax" might be better ?

2021-07-08 13:08 UTC, Mbrookesy requested changes

2021-07-08 13:08 UTC, Mbrookesy commented on resources/public/api/conf/1.0/application.raml
>        /{nino}:
after line 146 you need to include the delete raml file

2021-07-08 13:08 UTC, Mbrookesy commented on resources/public/api/conf/1.0/endpoints/cgtPpdOverrides/delete.raml
> +        description: Unique ID for operation tracking <br> String, 36 characters.
The entire file should be moved into the cgt folder which includes the amend.raml file

2021-07-08 13:17 UTC, merged