Mtdsa 12148
hmrc/individuals-income-received-api pull request #423
Opened 2022-07-06 07:09 UTC by abigail-houston-hmrc

Retrieve UK savings account annual summary - controller

2022-07-06 14:30 UTC, jeremystone requested changes
Couple of minor things but you will also need to add an integration test (under it/v1/endpoints).

Also RetrieveUkSavingsAccountRequestParserSpec.scala seems to have gotten deleted.

2022-07-06 14:30 UTC, jeremystone commented on app/v1/controllers/RetrieveUkSavingsAccountAnnualSummaryController.scala
> +      case UnauthorisedError       => Forbidden(Json.toJson(errorWrapper))
Please remove this line. We use separate auth to talk to backends so such a failure shouldn't translate to FORBIDDEN sent back to the vendor application. (Also remove case in ...ControllerSpec.)

2022-07-06 14:30 UTC, jeremystone commented on test/v1/controllers/RetrieveUkSavingsAccountAnnualSummaryControllerSpec.scala
> +  )
This is fine but don't forget that the HateoasFactory is mocked so it will return whatever it is told to return: it doesn't need to be the links in the spec for this test. 

See e.g. [here](https://github.com/hmrc/individuals-income-received-api/blob/b2c32604143c2a423be71c5fb2ad465801cea4f2/test/v1/controllers/CreateAmendUkDividendsAnnualSummaryControllerSpec.scala#L122) and [here](https://github.com/hmrc/individuals-income-received-api/blob/b2c32604143c2a423be71c5fb2ad465801cea4f2/test/v1/controllers/CreateAmendUkDividendsAnnualSummaryControllerSpec.scala#L130).

2022-07-08 10:02 UTC, abigail-houston-hmrc commented on test/v1/controllers/RetrieveUkSavingsAccountAnnualSummaryControllerSpec.scala
> +  )
I see your point. I'll leave for now, but not do so on the next feature

2022-07-08 10:06 UTC, abigail-houston-hmrc commented
I've added the integration test. The returns a vector, so I had to tweak the service to get it working.  I've also had to add a new overload for the onSuccess method i the DownstreamStub to account for the query parameters with no body. 

Please can you also confirm that the routes are as expected.

2022-07-08 11:17 UTC, jeremystone approved these changes

2022-07-08 13:21 UTC, merged