MTDSA-15268: Controller improvements for Employments and UK Savings Accounts endpoints
hmrc/individuals-income-received-api pull request #553
Opened 2023-03-23 11:55 UTC by GazalNebHMRC

2023-03-23 14:23 UTC, SamuelJacobsHMRC commented on app/v1/services/ListUkSavingsAccountsService.scala
> +      ec: ExecutionContext): Future[Either[ErrorWrapper, ResponseWrapper[ListUkSavingsAccountsResponse[UkSavingsAccount]]]] = {
Rather than `Future[Either[...]]` we can use `Future[ListUkSavingsAccountsServiceOutcome]`, adding the ListUkSavingsAccountsService to `service.package` (see [here](https://github.com/hmrc/individuals-income-received-api/blob/6918a0336e3e08e56e89af31d2e27155aa9d5106/app/v1/services/package.scala) and [here](https://github.com/hmrc/individuals-income-received-api/blob/6918a0336e3e08e56e89af31d2e27155aa9d5106/app/v1/services/RetrieveOtherCgtService.scala))

2023-03-23 14:23 UTC, SamuelJacobsHMRC commented on test/v1/controllers/AddCustomEmploymentControllerSpec.scala
> +          request = Some(requestBodyJson),
best we use the requestBody that we pass in to the method i.e. `request = requestBody`

2023-03-23 14:23 UTC, SamuelJacobsHMRC commented on test/v1/controllers/AddCustomEmploymentControllerSpec.scala
> +          request = Some(requestBodyJson),
(this will need changing for all controller specs)

2023-03-23 14:23 UTC, SamuelJacobsHMRC commented on test/v1/controllers/DeleteDividendsControllerSpec.scala
>    trait Test extends ControllerTest with AuditEventChecking[GenericAuditDetail] {
as we're here, for the sake of consistency can we move this Test trait to the bottom of the spec

2023-03-23 14:23 UTC, SamuelJacobsHMRC commented on test/v1/controllers/RetrieveEmploymentControllerSpec.scala
>      "return OK" when {
we have multiple sets of `return OK` here, they could all be within one set of brackets rather than the repetition

2023-03-23 14:23 UTC, SamuelJacobsHMRC commented on test/v1/mocks/connectors/MockDeleteCustomEmploymentConnector.scala
> +    def delete(request: DeleteCustomEmploymentRequest): CallHandler[Future[DownstreamOutcome[Unit]]] =
can we be a bit more consistent with what we are naming the request in these mock connectors? here it is called `request`, elsewhere it is called `requestData`

2023-03-23 14:23 UTC, SamuelJacobsHMRC commented on test/v1/mocks/services/MockCreateAmendUkSavingsAnnualSummaryService.scala
>          requestData: CreateAmendUkSavingsAnnualSummaryRequest): CallHandler[Future[Either[ErrorWrapper, ResponseWrapper[Unit]]]] = (
Once the `CreateAmendUkSavingsAnnualSummaryServiceOutcome` has been added, we should use it in this mock too. Same applies for all affected endpoints

2023-03-23 14:23 UTC, SamuelJacobsHMRC commented on test/v1/mocks/services/MockRetrieveEmploymentService.scala
> +    def retrieve(retrieveEmploymentRequest: RetrieveEmploymentRequest)
with the service mocks too we can be more consistent with what we are naming the request parameter

2023-03-23 17:44 UTC, GazalNebHMRC commented on app/v1/controllers/CreateAmendUkSavingsAnnualSummaryController.scala
> +            val respNoHateoas = resp.map {
As discussed, there was no response body being logged previously, which is essentially what this new method will return once the hateoas links are removed from the mtd response.

2023-03-24 09:47 UTC, SamuelJacobsHMRC commented on app/v1/controllers/ListEmploymentsController.scala
> +          .withResultCreator(ResultCreator.hateoasListWrapping(hateoasFactory)((_, _) => ListEmploymentHateoasData(nino, taxYear)))
need to update this to be `withHateoasResult`

2023-03-24 09:47 UTC, SamuelJacobsHMRC commented on app/v1/controllers/CreateAmendUkSavingsAnnualSummaryController.scala
> +            val respNoHateoas = resp.map {
Sorry, must have been miscommunication but I think it is best to completely remove the `respNoHateoas` (since it will return an empty JsValue and then update line 108 to be `AuditResponse(httpStatus = OK, response = Right(None))`

2023-03-24 10:00 UTC, GazalNebHMRC commented on app/v1/controllers/ListEmploymentsController.scala
> +          .withResultCreator(ResultCreator.hateoasListWrapping(hateoasFactory)((_, _) => ListEmploymentHateoasData(nino, taxYear)))
The reason I used .withResultCreator here is because it is uses .hateousListWrapping instead of
hateoasWrapping

2023-03-24 10:02 UTC, SamuelJacobsHMRC requested changes

2023-03-24 11:06 UTC, SamuelJacobsHMRC approved these changes

2023-03-24 11:07 UTC, merged